<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<AssemblyVersion>$(Version)</AssemblyVersion>
		<FileVersion>$(Version)</FileVersion>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageIcon>icon.nuget.jpg</PackageIcon>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>

		<DefineConstants>$(DefineConstants);WINDOWS</DefineConstants>
	</PropertyGroup>

	<Import Project="../../version.props"/>

	<ItemGroup>
		<PackageReference Include="Avalonia" />
		<PackageReference Include="Avalonia.Desktop" />
		<PackageReference Include="Avalonia.Controls.WebView"/>
		<PackageReference Include="Microsoft.Extensions.Configuration" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Ddon.Desktop.Core\Ddon.Desktop.Core.csproj"/>
	</ItemGroup>

</Project>
